### ISSUE TITLE
你好！请问一下你的控件我怎么可以直接使用？

### ISSUE THREAD

**Issue by zhehuiyl** [CCY0122/miuiweatherline#1]

**Comment by CCY0122** [comment]
1、下载源码，将本Module导入到你的AS里，你的Module依赖本Module后就可以直接用了
2、源码不多，也可以直接把代码复制过去(MiuiWeatherView.java、WeatherBean.java、res/values/attr.xml)
之后即可参照主页写的使用方法去使用
