### ISSUE TITLE
画线的时候，view的坐标改变了

### ISSUE THREAD

**Issue by kazarf007** [CCY0122/miuiweatherline#3]
参照着你的写的时候，发现当view的宽超过了屏幕时，我在（0,0）位置书写的文字就不见了，横坐标位置改变了。而且，时间轴的左右间隔也不见了，神奇

**Comment by CCY0122** [comment]
这个控件有个大缺点，就是宽度不受XML里的width控制，并且不会小于手机屏幕宽。所以如果它父布局宽不是全屏的，可能显示效果有问题。不知你是不是这个原因
