### ISSUE TITLE
第一次加载自定义控件数据显示不完全

### ISSUE THREAD

**Issue by li914** [CCY0122/miuiweatherline#4]
你好 请问当我第一次启动加载自定义布局 从网络请求的数据,可以看到log中数据已经加入自定义控件中,但是就是不显示数据,然后退出应用再进入,就可以完全显示了 请问你知道是怎么回事吗?

**Comment by CCY0122** [comment]
如果你是先setData(List)，然后等数据请求完成后再把数据add到List里的话，是不行的，因为为了减轻onDraw的负担，在第一次setData的时候就预先计算了一些用于绘制的参数。
所以只能在数据都获取完毕后再setData。当然你可以修改下源码，加一个类似notifyDataSetChanged的方法

**Comment by li914** [comment]
不是啊  我是先把数据add到list中后  然后在setData(list)的;
后来我想是不是因为数据加载的慢  我就把数据放到子线程处理,通过接口然后再拿回到ui线程后再设置setData(list),可是还是第一次不显示.
最后  我不用for循环把数据add到list中,手动添加数据add到list中,这样子正常显示
